version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: company-on-postgres
    environment:
      POSTGRES_DB: ragbot
      POSTGRES_USER: ragbot_user
      POSTGRES_PASSWORD: ragbot_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - company-on-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ragbot_user -d ragbot" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: company-on-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - company-on-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: company-on-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - company-on-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: company-on-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://ragbot_user:ragbot_password@postgres:5432/ragbot
      - REDIS_URL=redis://redis:6379
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - DEBUG=True
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ./backend:/app
    networks:
      - company-on-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: company-on-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - company-on-network
    restart: unless-stopped

  # Celery 워커
  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: company-on-celery-worker
    command: celery -A app.celery_app worker --loglevel=info --queues=document_processing,chat_processing,default
    environment:
      - DATABASE_URL=postgresql://ragbot_user:ragbot_password@postgres:5432/ragbot
      - REDIS_URL=redis://redis:6379/0
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=company-on-documents
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - ./backend:/app
    networks:
      - company-on-network
    restart: unless-stopped

  # Celery Beat (주기적 작업 스케줄러)
  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: company-on-celery-beat
    command: celery -A app.celery_app beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://ragbot_user:ragbot_password@postgres:5432/ragbot
      - REDIS_URL=redis://redis:6379/0
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=company-on-documents
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - ./backend:/app
    networks:
      - company-on-network
    restart: unless-stopped

  # Celery Flower (모니터링 도구)
  celery-flower:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: company-on-celery-flower
    command: celery -A app.celery_app flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://ragbot_user:ragbot_password@postgres:5432/ragbot
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
      - celery-worker
    volumes:
      - ./backend:/app
    networks:
      - company-on-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local

networks:
  company-on-network:
    driver: bridge
