"""add_failure_type_and_retryable_fields

Revision ID: 044e357629c6
Revises: cffc75cf8061
Create Date: 2025-09-10 05:36:33.922947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '044e357629c6'
down_revision: Union[str, Sequence[str], None] = 'cffc75cf8061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with default values first
    op.add_column('documents', sa.Column('failure_type', sa.String(length=20), nullable=True))
    op.add_column('documents', sa.Column('retryable', sa.Boolean(), nullable=True, default=True))
    op.add_column('upload_sessions', sa.Column('failure_type', sa.String(length=20), nullable=True))
    op.add_column('upload_sessions', sa.Column('retryable', sa.Boolean(), nullable=True, default=True))
    
    # Update existing records with default values
    op.execute("UPDATE documents SET retryable = true WHERE retryable IS NULL")
    op.execute("UPDATE upload_sessions SET retryable = true WHERE retryable IS NULL")
    
    # Make columns NOT NULL
    op.alter_column('documents', 'retryable', nullable=False)
    op.alter_column('upload_sessions', 'retryable', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_sessions', 'retryable')
    op.drop_column('upload_sessions', 'failure_type')
    op.drop_column('documents', 'retryable')
    op.drop_column('documents', 'failure_type')
    # ### end Alembic commands ###
