"""add_chunk_type_and_metadata_to_document_chunks

Revision ID: 3cc620931c80
Revises: 9c04c993799b
Create Date: 2025-09-08 17:31:19.272021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '3cc620931c80'
down_revision: Union[str, Sequence[str], None] = '9c04c993799b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)  # 이미 존재하는 인덱스
    op.alter_column('embedding_cache', 'embedding',
               existing_type=Vector(dim=768),
               type_=Vector(dim=384),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('embedding_cache', 'embedding',
               existing_type=Vector(dim=384),
               type_=Vector(dim=768),
               existing_nullable=False)
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    # ### end Alembic commands ###
