"""add_chunk_type_field

Revision ID: 3d6f4fd1e6d3
Revises: 3cc620931c80
Create Date: 2025-09-08 17:32:42.066706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6f4fd1e6d3'
down_revision: Union[str, Sequence[str], None] = '3cc620931c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1. 먼저 nullable=True로 컬럼 추가
    op.add_column('document_chunks', sa.Column('chunk_type', sa.String(length=50), nullable=True))
    
    # 2. 기존 데이터에 기본값 설정
    op.execute("UPDATE document_chunks SET chunk_type = 'text' WHERE chunk_type IS NULL")
    
    # 3. NOT NULL 제약조건 추가
    op.alter_column('document_chunks', 'chunk_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'chunk_type')
    # ### end Alembic commands ###
