"""Add upload_sessions table for status tracking

Revision ID: 9c04c993799b
Revises: 870f3087582d
Create Date: 2025-09-07 14:29:01.214012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c04c993799b'
down_revision: Union[str, Sequence[str], None] = '870f3087582d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_sessions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_size', sa.BigInteger(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_upload_sessions_created', 'upload_sessions', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_upload_sessions_status', 'upload_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_upload_sessions_id'), 'upload_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_upload_sessions_id'), table_name='upload_sessions')
    op.drop_index('idx_upload_sessions_status', table_name='upload_sessions')
    op.drop_index('idx_upload_sessions_created', table_name='upload_sessions')
    op.drop_table('upload_sessions')
    # ### end Alembic commands ###
