"""add_error_message_to_document

Revision ID: aa1190dbf366
Revises: 3d6f4fd1e6d3
Create Date: 2025-09-09 15:53:19.264539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'aa1190dbf366'
down_revision: Union[str, Sequence[str], None] = '3d6f4fd1e6d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_session_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=384),
               type_=pgvector.sqlalchemy.Vector(dim=768),
               existing_nullable=False)
    op.add_column('documents', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'error_message')
    op.alter_column('chat_session_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=768),
               type_=pgvector.sqlalchemy.Vector(dim=384),
               existing_nullable=False)
    # ### end Alembic commands ###
