"""Add description field to chat_sessions

Revision ID: cffc75cf8061
Revises: aa1190dbf366
Create Date: 2025-09-09 22:37:55.334935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cffc75cf8061'
down_revision: Union[str, Sequence[str], None] = 'aa1190dbf366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'description')
    # ### end Alembic commands ###
